'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowDown,ArrowUp,Copy,Check,Menu,X,Plus,LayoutGrid,MoreHorizontal} from 'lucide-react';
import {portfolio as p} from './portfolio.config';
import {Dialog,DialogContent,DialogTitle} from '@/components/ui/dialog';
type Project = typeof p.projects[number];
const validUrl=(url:string)=>/^https:\/\//.test(url);
function Preview({type}:{type:string}){
 return <div className={`mockup ${type}`} aria-hidden="true"><div className="window-bar"><span/><span/><span/><small>{type==='dashboard'?'clarity / overview':type==='commerce'?'objects / collection':'dayframe / workspace'}</small></div>
 {type==='dashboard'?<div className="dash-layout"><aside><b>c.</b><LayoutGrid size={15}/><i/><i/><i/></aside><div className="dash-content"><div className="mock-title"><b>Overview</b><small>This month ↗</small></div><div className="metrics"><div><small>Total revenue</small><strong>$24,680</strong></div><div><small>Active users</small><strong>1,842</strong></div><div><small>Growth</small><strong>+18.6%</strong></div></div><div className="chart"><small>Revenue overview</small><svg viewBox="0 0 450 110"><path d="M0 90H450M0 55H450M0 20H450" stroke="#ddd" strokeDasharray="3 5"/><path d="M0 95L30 85 65 88 100 62 135 70 170 45 205 52 240 34 275 40 310 20 345 29 385 8 420 13 450 0" fill="none" stroke="#252525" strokeWidth="3"/></svg></div><div className="mock-lines"><i/><i/><i/></div></div></div>:
 type==='commerce'?<div className="shop-content"><div className="shop-nav"><b>objects®</b><small>Collection &nbsp; About &nbsp; Bag (0)</small></div><div className="shop-heading"><span>Less, but<br/><em>considered.</em></span><small>EVERYDAY ESSENTIALS<br/>COLLECTION — 001</small></div><div className="products">{['01','02','03'].map((v,i)=><div key={v}><div className={`product-art art-${i}`}><span/><span/><span/></div><div className="product-label"><small>Study {v}</small><small>Objects</small></div></div>)}</div></div>:
 <div className="tasks-content"><div className="task-top"><b>dayframe<span> / personal space</span></b><MoreHorizontal size={20}/></div><div className="mock-title"><b>A little more focus.</b><small>Monday, 06</small></div><div className="task-columns">{['To do','In progress','Done'].map((v,i)=><div key={v}><small>{v} <span>{i===0?'3':'2'}</span></small>{[0,1,...(i===0?[2]:[])].map((k)=><div className="task-card" key={k}><span className="task-tag">{['Design','Build','Explore'][k]}</span><b>{['Refine the details','Make space for ideas','Start something new'][(i+k)%3]}</b><div><i/><small>Today</small></div></div>)}<div className="add-task"><Plus size={12}/> Add task</div></div>)}</div></div>}
 </div>
}
function Geometry(){return <div className="geometry" aria-hidden="true"><div className="geo-cross cross-a">+</div><div className="geo-cross cross-b">+</div><svg viewBox="0 0 500 500" fill="none"><g className="orbital">{Array.from({length:18},(_,i)=><ellipse key={i} cx="250" cy="250" rx="178" ry={25+i*8.8} transform={`rotate(${i*10} 250 250)`} stroke={i%3===0?'#969696':'#484848'} strokeWidth=".8"/>)}</g><circle cx="250" cy="250" r="216" stroke="#242424" strokeDasharray="2 8"/><path d="M10 250H490M250 10V490" stroke="#222"/></svg><div className="geo-caption"><span>FIG. 01 — IDEAS IN MOTION</span><span>360°</span></div></div>}
export default function Home(){
 const [scrolled,setScrolled]=useState(false),[selected,setSelected]=useState<Project|null>(null),[copied,setCopied]=useState(false),[copyMessage,setCopyMessage]=useState('');
 const menu=useRef<HTMLDialogElement>(null),lastFocus=useRef<HTMLElement|null>(null),menuButton=useRef<HTMLButtonElement>(null);
 const emailReady=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email);
 useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>24);onScroll();window.addEventListener('scroll',onScroll,{passive:true});const media=window.matchMedia('(prefers-reduced-motion: reduce)');let observer:IntersectionObserver|undefined;if(!media.matches&&'IntersectionObserver' in window){observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer?.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>{el.classList.add('will-reveal');observer?.observe(el)})}return()=>{window.removeEventListener('scroll',onScroll);observer?.disconnect()}},[]);
 const closeProject=()=>setSelected(null);
 const closeMenu=()=>{menu.current?.close();document.body.style.overflow='';menuButton.current?.focus()};
 useEffect(()=>{const q=window.matchMedia('(min-width: 701px)');const fn=()=>{if(q.matches&&menu.current?.open)closeMenu()};q.addEventListener('change',fn);return()=>q.removeEventListener('change',fn)},[]);
 async function copyEmail(){try{await navigator.clipboard.writeText(p.email);setCopied(true);setCopyMessage('Email berhasil disalin.');setTimeout(()=>setCopied(false),2400)}catch{setCopyMessage('Tidak dapat menyalin otomatis. Pilih dan salin alamat email di atas.')}}
 return <><a className="skip-link" href="#main">Lewati ke konten</a><header className={scrolled?'scrolled':''}><a href="#top" className="wordmark" aria-label="Kembali ke awal"><span className="brand-mark">g<span>.</span></span><span>{p.name}</span></a><nav aria-label="Navigasi utama"><a href="#about">About</a><a href="#projects">Projects <sup>03</sup></a><a href="#contact">Contact <ArrowUpRight size={16}/></a></nav><button className="mobile-toggle" ref={menuButton} aria-label="Buka menu" aria-haspopup="dialog" onClick={()=>{menu.current?.showModal();document.body.style.overflow='hidden'}}><Menu/></button></header>
 <main id="main"><section className="hero container" id="top"><div className="hero-meta enter"><span>PERSONAL PORTFOLIO</span><span>DESIGN × DEVELOPMENT</span></div><div className="hero-main"><div className="hero-copy"><h1 className="enter">Turning ideas into<br/><span>digital</span><br/>experiences<span className="period">.</span></h1><div className="hero-intro enter"><p>Hi, I’m {p.name}.<br/><span>{p.profession}</span></p><div className="hero-actions"><a className="button primary" href="#projects">View Projects <ArrowUpRight size={18}/></a><a className="text-link" href="#contact">Let’s Talk <ArrowUpRight size={18}/></a></div></div></div><Geometry/></div><div className="hero-bottom enter"><a href="#about"><ArrowDown size={16}/><span>SCROLL TO EXPLORE</span></a><span>THOUGHTFUL DESIGN. PURPOSEFUL CODE.</span></div></section>
 <section className="about container section-grid" id="about"><div className="section-label reveal"><span>01 / ABOUT</span><span className="tiny-line"/></div><div className="about-body"><h2 className="reveal">A little<br/><span>about me.</span></h2><p className="about-description reveal">{p.description}</p><div className="skills-title reveal">MY TOOLKIT</div><div className="skills">{p.skills.map((s,i)=><div className="reveal" style={{transitionDelay:`${i*65}ms`}} key={s}><span>0{i+1}</span>{s}<Plus size={17}/></div>)}</div></div></section>
 <section className="projects container" id="projects"><div className="projects-heading reveal"><div><div className="section-label">02 / SELECTED WORK</div><h2>Selected<br/><span>projects.</span></h2></div><p>Three ideas, different possibilities.</p></div><div className="project-list">{p.projects.map((project,i)=><article className={`project reveal project-${i}`} key={project.id}><button className="project-visual" aria-label={`Buka detail ${project.title}`} onClick={e=>{lastFocus.current=e.currentTarget;setSelected(project)}}><div className="preview-label"><span>CONCEPT / {project.id}</span><span>DEMO PROJECT</span></div><Preview type={project.type}/><span className="preview-bottom">{project.category}<span className="round-arrow"><ArrowUpRight size={21}/></span></span></button><div className="project-info"><span className="project-number">/{project.id}</span><div><span className="eyebrow">{project.category}</span><h3><button onClick={e=>{lastFocus.current=e.currentTarget;setSelected(project)}}>{project.title}<ArrowUpRight size={28}/></button></h3><p>{project.description}</p><div className="tags">{project.tags.map(t=><span key={t}>{t}</span>)}</div><button className="project-detail" onClick={e=>{lastFocus.current=e.currentTarget;setSelected(project)}}>Explore concept <ArrowUpRight size={17}/></button></div></div></article>)}</div></section>
 <section className="contact" id="contact"><div className="container"><div className="section-label reveal">03 / GET IN TOUCH</div><h2 className="reveal">Have something<br/>in mind?<br/><span>Let’s build it.</span><ArrowUpRight className="contact-arrow" strokeWidth={1}/></h2><div className="contact-bottom reveal"><div><span className="eyebrow">START A CONVERSATION</span><div className="email-row">{emailReady?<><a href={`mailto:${p.email}`}>{p.email}</a><button aria-label="Salin email" onClick={copyEmail}>{copied?<Check/>:<Copy size={21}/>}</button></>:<><span>[Email kamu]</span><button disabled aria-label="Salin email — isi email terlebih dahulu"><Copy size={21}/></button></>}</div>{emailReady?<a href={`mailto:${p.email}`} className="contact-mail">Let’s Talk <ArrowUpRight size={17}/></a>:<p className="placeholder-note">Email belum diisi.</p>}<p className="copy-feedback" role="status" aria-live="polite">{copyMessage}</p></div><div className="socials">{validUrl(p.github)?<a href={p.github} target="_blank" rel="noreferrer">GitHub<ArrowUpRight size={18}/></a>:<span>GitHub<small>{p.githubLabel} · Link belum lengkap</small></span>}</div></div></div></section></main>
 <footer className="container"><span>© {new Date().getFullYear()} {p.name}</span><span className="footer-center">DESIGNED WITH INTENTION.</span><a href="#top">Back to top <ArrowUp size={16}/></a></footer>
 <dialog className="mobile-menu" ref={menu} aria-labelledby="menu-title" onCancel={e=>{e.preventDefault();closeMenu()}} onClick={e=>{if(e.target===menu.current)closeMenu()}}><div><div className="menu-head"><span id="menu-title">NAVIGATION</span><button aria-label="Tutup menu" onClick={closeMenu}><X/></button></div><nav aria-label="Navigasi mobile">{['About','Projects','Contact'].map((v,i)=><a href={`#${v.toLowerCase()}`} key={v} onClick={closeMenu}><small>0{i+1}</small>{v}<ArrowUpRight/></a>)}</nav><span>{p.name}</span></div></dialog>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)closeProject()}}><DialogContent className="project-modal" showCloseButton={false} aria-describedby={undefined} onCloseAutoFocus={e=>{e.preventDefault();lastFocus.current?.focus()}}>{selected&&<div className="modal-inner"><div className="modal-top"><span className="eyebrow">DEMO PROJECT / {selected.id}</span><button autoFocus aria-label="Tutup detail proyek" onClick={closeProject}><X/></button></div><DialogTitle asChild><h2 id="project-title">{selected.title}</h2></DialogTitle><p>{selected.description}</p><p className="demo-note">Konten demo untuk diganti. Preview berikut adalah konsep antarmuka, bukan aplikasi lengkap.</p><Preview type={selected.type}/><h3>Concept features</h3><ul>{selected.features.map(f=><li key={f}>{f}</li>)}</ul><h3>Proposed stack</h3><div className="tags">{selected.tags.map(t=><span key={t}>{t}</span>)}</div><div className="modal-links">{[['Live demo',selected.demoUrl],['Repository',selected.repositoryUrl]].map(([label,url])=>validUrl(url)?<a key={label} href={url} target="_blank" rel="noreferrer">{label} <ArrowUpRight size={16}/></a>:<div key={label}><span>{label}</span><small>Coming soon</small></div>)}</div></div>}</DialogContent></Dialog>
 </>
}
